### ISSUE TITLE
Would be nice with windows binaries

### ISSUE THREAD

**Issue by henke443** [mmalka/TheNoobBot#12]
Can you please build this source for the plebs? I want to experiment with creating profiles and stuff for educational purposes.

**Comment by mmalka** [comment]
Each compilation of the bot target a very specific wow binary version, you wont be able to do anything with it even compiled. It's very much outdated.

**Comment by henke443** [comment]
I understand but there's a demand for bots for outdated versions of wow. This one seemed really good and it's a shame to let such good effort go to waste :)

**Comment by mmalka** [comment]
https://github.com/mmalka/TheNoobBot/commits/master/The%20Noob%20Bot/nManager/Wow/Patchables/Addresses.cs

There is an history of all wow patch that was supported, I don't give support for this project. Anyone with Visual Studio and a little bit of practice is able to fix any compilation issue that would come.

I think you first need to compile the C++ projects if you have problem compiling.

It wont give you a working bot. Perhaps for that specific version and even, you'd need to make sure you rollback to the version of TNB that supported that version of wow and losing features in the process because you wouldn't be sure of wether you're losing "patch specific code" such as "what is a spell in game for X or Y patch version" (those structure evolves)

Also, you'd have to kick the "remote server" part because the bot is gonna want to verify your account so you have to dig a bit and disable those protections since there is no server to talk to.

I think the PHP code is somewhere but it's quicker to just disable that.
